# Generated by Django 6.0 on 2025-12-09 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='captures/')),
                ('product_name', models.CharField(blank=True, max_length=512)),
                ('unit', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
