# Generated by Django 6.0 on 2025-12-09 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='captures/')),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Medicine', 'Medicine'), ('Drinks', 'Drinks'), ('Hygiene', 'Hygiene'), ('Insecticide', 'Insecticide'), ('Cleanings', 'Cleanings')], max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
