# Generated by Django 6.0 on 2025-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcapture',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Medicine', 'Medicine'), ('Drinks', 'Drinks'), ('Hygiene', 'Hygiene'), ('Insecticide', 'Insecticide'), ('Cleanings', 'Cleanings'), ('School/Office Supplies', 'School/Office Supplies')], max_length=30),
        ),
    ]
