# Generated by Django 6.0 on 2025-12-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productcapture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcapture',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Medicine', 'Medicine'), ('Hygiene', 'Hygiene'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Insecticide', 'Insecticide'), ('School Supplies', 'School Supplies'), ('Office Supplies', 'Office Supplies'), ('Tobacco', 'Tobacco'), ('Alcohol', 'Alcohol'), ('Frozen Goods', 'Frozen Goods'), ('Bread & Pastries', 'Bread & Pastries'), ('Baby Products', 'Baby Products'), ('Pet Supplies', 'Pet Supplies'), ('Hardware & Electrical', 'Hardware & Electrical'), ('Clothing & Accessories', 'Clothing & Accessories'), ('Mobile Load & E-Services', 'Mobile Load & E-Services'), ('Rice & Grains', 'Rice & Grains')], max_length=30),
        ),
    ]
